### ISSUE TITLE
Please support Map<string,obj> deserialization

### ISSUE THREAD

**Issue by katatunix** [u1roh/FSharp.JSerde#2]
When I deserialize a valid JSON string to a `Map<string,obj>`:

    let x : Map<string, obj> = """{"hello":"world"}""" |> JSerde.fromJsonString JSerde.Config.Default

I got this exception:

    FSharp.JSerde.JSerde+TypeMismatch: `System.Object` doesn't match with "world"

Can you please support this?

Note that the serialization works perfectly.

**Comment by u1roh** [comment]
@katatunix Sorry for the late reply.
I've just updated the library. The deserialization of this issue is supported at https://github.com/u1roh/FSharp.JSerde/commit/51186f297748b3c84cdb98add5a8862199b73964 .
You can use it in v0.0.6. https://www.nuget.org/packages/FSharp.JSerde/
